<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: KS.proto

namespace KuaiShouPack;

if (false) {
    /**
     * This class is deprecated. Use KuaiShouPack\SocketMessage\CompressionType instead.
     * @deprecated
     */
    class SocketMessage_CompressionType {}
}
class_exists(SocketMessage\CompressionType::class);
@trigger_error('KuaiShouPack\SocketMessage_CompressionType is deprecated and will be removed in the next major release. Use KuaiShouPack\SocketMessage\CompressionType instead', E_USER_DEPRECATED);

