<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: KS.proto

namespace KuaiShouPack;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>KuaiShouPack.WebGiftFeed</code>
 */
class WebGiftFeed extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string id = 1;</code>
     */
    private $id = '';
    /**
     * Generated from protobuf field <code>.KuaiShouPack.SimpleUserInfo user = 2;</code>
     */
    private $user = null;
    /**
     * Generated from protobuf field <code>uint64 time = 3;</code>
     */
    private $time = 0;
    /**
     * Generated from protobuf field <code>uint32 giftId = 4;</code>
     */
    private $giftId = 0;
    /**
     * Generated from protobuf field <code>uint64 sortRank = 5;</code>
     */
    private $sortRank = 0;
    /**
     * Generated from protobuf field <code>string mergeKey = 6;</code>
     */
    private $mergeKey = '';
    /**
     * Generated from protobuf field <code>uint32 batchSize = 7;</code>
     */
    private $batchSize = 0;
    /**
     * Generated from protobuf field <code>uint32 comboCount = 8;</code>
     */
    private $comboCount = 0;
    /**
     * Generated from protobuf field <code>uint32 rank = 9;</code>
     */
    private $rank = 0;
    /**
     * Generated from protobuf field <code>uint64 expireDuration = 10;</code>
     */
    private $expireDuration = 0;
    /**
     * Generated from protobuf field <code>uint64 clientTimestamp = 11;</code>
     */
    private $clientTimestamp = 0;
    /**
     * Generated from protobuf field <code>uint64 slotDisplayDuration = 12;</code>
     */
    private $slotDisplayDuration = 0;
    /**
     * Generated from protobuf field <code>uint32 starLevel = 13;</code>
     */
    private $starLevel = 0;
    /**
     * Generated from protobuf field <code>.KuaiShouPack.WebGiftFeed.StyleType styleType = 14;</code>
     */
    private $styleType = 0;
    /**
     * Generated from protobuf field <code>.KuaiShouPack.WebLiveAssistantType liveAssistantType = 15;</code>
     */
    private $liveAssistantType = 0;
    /**
     * Generated from protobuf field <code>string deviceHash = 16;</code>
     */
    private $deviceHash = '';
    /**
     * Generated from protobuf field <code>bool danmakuDisplay = 17;</code>
     */
    private $danmakuDisplay = false;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $id
     *     @type \KuaiShouPack\SimpleUserInfo $user
     *     @type int|string $time
     *     @type int $giftId
     *     @type int|string $sortRank
     *     @type string $mergeKey
     *     @type int $batchSize
     *     @type int $comboCount
     *     @type int $rank
     *     @type int|string $expireDuration
     *     @type int|string $clientTimestamp
     *     @type int|string $slotDisplayDuration
     *     @type int $starLevel
     *     @type int $styleType
     *     @type int $liveAssistantType
     *     @type string $deviceHash
     *     @type bool $danmakuDisplay
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\KS::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string id = 1;</code>
     * @return string
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Generated from protobuf field <code>string id = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkString($var, True);
        $this->id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.KuaiShouPack.SimpleUserInfo user = 2;</code>
     * @return \KuaiShouPack\SimpleUserInfo
     */
    public function getUser()
    {
        return $this->user;
    }

    /**
     * Generated from protobuf field <code>.KuaiShouPack.SimpleUserInfo user = 2;</code>
     * @param \KuaiShouPack\SimpleUserInfo $var
     * @return $this
     */
    public function setUser($var)
    {
        GPBUtil::checkMessage($var, \KuaiShouPack\SimpleUserInfo::class);
        $this->user = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 time = 3;</code>
     * @return int|string
     */
    public function getTime()
    {
        return $this->time;
    }

    /**
     * Generated from protobuf field <code>uint64 time = 3;</code>
     * @param int|string $var
     * @return $this
     */
    public function setTime($var)
    {
        GPBUtil::checkUint64($var);
        $this->time = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 giftId = 4;</code>
     * @return int
     */
    public function getGiftId()
    {
        return $this->giftId;
    }

    /**
     * Generated from protobuf field <code>uint32 giftId = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setGiftId($var)
    {
        GPBUtil::checkUint32($var);
        $this->giftId = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 sortRank = 5;</code>
     * @return int|string
     */
    public function getSortRank()
    {
        return $this->sortRank;
    }

    /**
     * Generated from protobuf field <code>uint64 sortRank = 5;</code>
     * @param int|string $var
     * @return $this
     */
    public function setSortRank($var)
    {
        GPBUtil::checkUint64($var);
        $this->sortRank = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string mergeKey = 6;</code>
     * @return string
     */
    public function getMergeKey()
    {
        return $this->mergeKey;
    }

    /**
     * Generated from protobuf field <code>string mergeKey = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setMergeKey($var)
    {
        GPBUtil::checkString($var, True);
        $this->mergeKey = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 batchSize = 7;</code>
     * @return int
     */
    public function getBatchSize()
    {
        return $this->batchSize;
    }

    /**
     * Generated from protobuf field <code>uint32 batchSize = 7;</code>
     * @param int $var
     * @return $this
     */
    public function setBatchSize($var)
    {
        GPBUtil::checkUint32($var);
        $this->batchSize = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 comboCount = 8;</code>
     * @return int
     */
    public function getComboCount()
    {
        return $this->comboCount;
    }

    /**
     * Generated from protobuf field <code>uint32 comboCount = 8;</code>
     * @param int $var
     * @return $this
     */
    public function setComboCount($var)
    {
        GPBUtil::checkUint32($var);
        $this->comboCount = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 rank = 9;</code>
     * @return int
     */
    public function getRank()
    {
        return $this->rank;
    }

    /**
     * Generated from protobuf field <code>uint32 rank = 9;</code>
     * @param int $var
     * @return $this
     */
    public function setRank($var)
    {
        GPBUtil::checkUint32($var);
        $this->rank = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 expireDuration = 10;</code>
     * @return int|string
     */
    public function getExpireDuration()
    {
        return $this->expireDuration;
    }

    /**
     * Generated from protobuf field <code>uint64 expireDuration = 10;</code>
     * @param int|string $var
     * @return $this
     */
    public function setExpireDuration($var)
    {
        GPBUtil::checkUint64($var);
        $this->expireDuration = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 clientTimestamp = 11;</code>
     * @return int|string
     */
    public function getClientTimestamp()
    {
        return $this->clientTimestamp;
    }

    /**
     * Generated from protobuf field <code>uint64 clientTimestamp = 11;</code>
     * @param int|string $var
     * @return $this
     */
    public function setClientTimestamp($var)
    {
        GPBUtil::checkUint64($var);
        $this->clientTimestamp = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 slotDisplayDuration = 12;</code>
     * @return int|string
     */
    public function getSlotDisplayDuration()
    {
        return $this->slotDisplayDuration;
    }

    /**
     * Generated from protobuf field <code>uint64 slotDisplayDuration = 12;</code>
     * @param int|string $var
     * @return $this
     */
    public function setSlotDisplayDuration($var)
    {
        GPBUtil::checkUint64($var);
        $this->slotDisplayDuration = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 starLevel = 13;</code>
     * @return int
     */
    public function getStarLevel()
    {
        return $this->starLevel;
    }

    /**
     * Generated from protobuf field <code>uint32 starLevel = 13;</code>
     * @param int $var
     * @return $this
     */
    public function setStarLevel($var)
    {
        GPBUtil::checkUint32($var);
        $this->starLevel = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.KuaiShouPack.WebGiftFeed.StyleType styleType = 14;</code>
     * @return int
     */
    public function getStyleType()
    {
        return $this->styleType;
    }

    /**
     * Generated from protobuf field <code>.KuaiShouPack.WebGiftFeed.StyleType styleType = 14;</code>
     * @param int $var
     * @return $this
     */
    public function setStyleType($var)
    {
        GPBUtil::checkEnum($var, \KuaiShouPack\WebGiftFeed_StyleType::class);
        $this->styleType = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.KuaiShouPack.WebLiveAssistantType liveAssistantType = 15;</code>
     * @return int
     */
    public function getLiveAssistantType()
    {
        return $this->liveAssistantType;
    }

    /**
     * Generated from protobuf field <code>.KuaiShouPack.WebLiveAssistantType liveAssistantType = 15;</code>
     * @param int $var
     * @return $this
     */
    public function setLiveAssistantType($var)
    {
        GPBUtil::checkEnum($var, \KuaiShouPack\WebLiveAssistantType::class);
        $this->liveAssistantType = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string deviceHash = 16;</code>
     * @return string
     */
    public function getDeviceHash()
    {
        return $this->deviceHash;
    }

    /**
     * Generated from protobuf field <code>string deviceHash = 16;</code>
     * @param string $var
     * @return $this
     */
    public function setDeviceHash($var)
    {
        GPBUtil::checkString($var, True);
        $this->deviceHash = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool danmakuDisplay = 17;</code>
     * @return bool
     */
    public function getDanmakuDisplay()
    {
        return $this->danmakuDisplay;
    }

    /**
     * Generated from protobuf field <code>bool danmakuDisplay = 17;</code>
     * @param bool $var
     * @return $this
     */
    public function setDanmakuDisplay($var)
    {
        GPBUtil::checkBool($var);
        $this->danmakuDisplay = $var;

        return $this;
    }

}

