<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: KS.proto

namespace KuaiShouPack;

if (false) {
    /**
     * This class is deprecated. Use KuaiShouPack\WebGiftFeed\StyleType instead.
     * @deprecated
     */
    class WebGiftFeed_StyleType {}
}
class_exists(WebGiftFeed\StyleType::class);
@trigger_error('KuaiShouPack\WebGiftFeed_StyleType is deprecated and will be removed in the next major release. Use KuaiShouPack\WebGiftFeed\StyleType instead', E_USER_DEPRECATED);

