<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: KS.proto

namespace KuaiShouPack;

if (false) {
    /**
     * This class is deprecated. Use KuaiShouPack\WebSystemNoticeFeed\DisplayType instead.
     * @deprecated
     */
    class WebSystemNoticeFeed_DisplayType {}
}
class_exists(WebSystemNoticeFeed\DisplayType::class);
@trigger_error('KuaiShouPack\WebSystemNoticeFeed_DisplayType is deprecated and will be removed in the next major release. Use KuaiShouPack\WebSystemNoticeFeed\DisplayType instead', E_USER_DEPRECATED);

