<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: KuaiShouLive.proto

namespace KuaiShouLive\WebSystemNoticeFeed;

/**
 * Protobuf type <code>KuaiShouLive.WebSystemNoticeFeed.DisplayType</code>
 */
class DisplayType
{
    /**
     * Generated from protobuf enum <code>UNKNOWN_DISPLAY_TYPE = 0;</code>
     */
    const UNKNOWN_DISPLAY_TYPE = 0;
    /**
     * Generated from protobuf enum <code>COMMENT = 1;</code>
     */
    const COMMENT = 1;
    /**
     * Generated from protobuf enum <code>ALERT = 2;</code>
     */
    const ALERT = 2;
    /**
     * Generated from protobuf enum <code>TOAST = 3;</code>
     */
    const TOAST = 3;
}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(DisplayType::class, \KuaiShouLive\WebSystemNoticeFeed_DisplayType::class);

