<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: KS.proto

namespace KuaiShouPack\WebGiftFeed;

/**
 * Protobuf type <code>KuaiShouPack.WebGiftFeed.StyleType</code>
 */
class StyleType
{
    /**
     * Generated from protobuf enum <code>UNKNOWN_STYLE = 0;</code>
     */
    const UNKNOWN_STYLE = 0;
    /**
     * Generated from protobuf enum <code>BATCH_STAR_0 = 1;</code>
     */
    const BATCH_STAR_0 = 1;
    /**
     * Generated from protobuf enum <code>BATCH_STAR_1 = 2;</code>
     */
    const BATCH_STAR_1 = 2;
    /**
     * Generated from protobuf enum <code>BATCH_STAR_2 = 3;</code>
     */
    const BATCH_STAR_2 = 3;
    /**
     * Generated from protobuf enum <code>BATCH_STAR_3 = 4;</code>
     */
    const BATCH_STAR_3 = 4;
    /**
     * Generated from protobuf enum <code>BATCH_STAR_4 = 5;</code>
     */
    const BATCH_STAR_4 = 5;
    /**
     * Generated from protobuf enum <code>BATCH_STAR_5 = 6;</code>
     */
    const BATCH_STAR_5 = 6;
    /**
     * Generated from protobuf enum <code>BATCH_STAR_6 = 7;</code>
     */
    const BATCH_STAR_6 = 7;
}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(StyleType::class, \KuaiShouPack\WebGiftFeed_StyleType::class);

