<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: KuaiShouLive.proto

namespace KuaiShouLive;

/**
 * Protobuf type <code>KuaiShouLive.ClientId</code>
 */
class ClientId
{
    /**
     * Generated from protobuf enum <code>NONE = 0;</code>
     */
    const NONE = 0;
    /**
     * Generated from protobuf enum <code>IPHONE = 1;</code>
     */
    const IPHONE = 1;
    /**
     * Generated from protobuf enum <code>ANDROID = 2;</code>
     */
    const ANDROID = 2;
    /**
     * Generated from protobuf enum <code>WEB = 3;</code>
     */
    const WEB = 3;
    /**
     * Generated from protobuf enum <code>PC = 6;</code>
     */
    const PC = 6;
    /**
     * Generated from protobuf enum <code>IPHONE_LIVE_MATE = 8;</code>
     */
    const IPHONE_LIVE_MATE = 8;
    /**
     * Generated from protobuf enum <code>ANDROID_LIVE_MATE = 9;</code>
     */
    const ANDROID_LIVE_MATE = 9;
}

