<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: KS.proto

namespace KuaiShouLive;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>KuaiShouLive.CSPing</code>
 */
class CSPing extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string echoData = 1;</code>
     */
    private $echoData = '';
    /**
     * Generated from protobuf field <code>.KuaiShouLive.ClientId clientId = 2;</code>
     */
    private $clientId = 0;
    /**
     * Generated from protobuf field <code>string deviceId = 3;</code>
     */
    private $deviceId = '';
    /**
     * Generated from protobuf field <code>string appVer = 4;</code>
     */
    private $appVer = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $echoData
     *     @type int $clientId
     *     @type string $deviceId
     *     @type string $appVer
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\KS::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string echoData = 1;</code>
     * @return string
     */
    public function getEchoData()
    {
        return $this->echoData;
    }

    /**
     * Generated from protobuf field <code>string echoData = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setEchoData($var)
    {
        GPBUtil::checkString($var, True);
        $this->echoData = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.KuaiShouLive.ClientId clientId = 2;</code>
     * @return int
     */
    public function getClientId()
    {
        return $this->clientId;
    }

    /**
     * Generated from protobuf field <code>.KuaiShouLive.ClientId clientId = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setClientId($var)
    {
        GPBUtil::checkEnum($var, \KuaiShouLive\ClientId::class);
        $this->clientId = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string deviceId = 3;</code>
     * @return string
     */
    public function getDeviceId()
    {
        return $this->deviceId;
    }

    /**
     * Generated from protobuf field <code>string deviceId = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setDeviceId($var)
    {
        GPBUtil::checkString($var, True);
        $this->deviceId = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string appVer = 4;</code>
     * @return string
     */
    public function getAppVer()
    {
        return $this->appVer;
    }

    /**
     * Generated from protobuf field <code>string appVer = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setAppVer($var)
    {
        GPBUtil::checkString($var, True);
        $this->appVer = $var;

        return $this;
    }

}

