<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: KS.proto

namespace KuaiShouLive;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>KuaiShouLive.CSWebEnterRoom</code>
 */
class CSWebEnterRoom extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string token = 1;</code>
     */
    private $token = '';
    /**
     * Generated from protobuf field <code>string liveStreamId = 2;</code>
     */
    private $liveStreamId = '';
    /**
     * Generated from protobuf field <code>uint32 reconnectCount = 3;</code>
     */
    private $reconnectCount = 0;
    /**
     * Generated from protobuf field <code>uint32 lastErrorCode = 4;</code>
     */
    private $lastErrorCode = 0;
    /**
     * Generated from protobuf field <code>string expTag = 5;</code>
     */
    private $expTag = '';
    /**
     * Generated from protobuf field <code>string attach = 6;</code>
     */
    private $attach = '';
    /**
     * Generated from protobuf field <code>string pageId = 7;</code>
     */
    private $pageId = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $token
     *     @type string $liveStreamId
     *     @type int $reconnectCount
     *     @type int $lastErrorCode
     *     @type string $expTag
     *     @type string $attach
     *     @type string $pageId
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\KS::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string token = 1;</code>
     * @return string
     */
    public function getToken()
    {
        return $this->token;
    }

    /**
     * Generated from protobuf field <code>string token = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setToken($var)
    {
        GPBUtil::checkString($var, True);
        $this->token = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string liveStreamId = 2;</code>
     * @return string
     */
    public function getLiveStreamId()
    {
        return $this->liveStreamId;
    }

    /**
     * Generated from protobuf field <code>string liveStreamId = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setLiveStreamId($var)
    {
        GPBUtil::checkString($var, True);
        $this->liveStreamId = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 reconnectCount = 3;</code>
     * @return int
     */
    public function getReconnectCount()
    {
        return $this->reconnectCount;
    }

    /**
     * Generated from protobuf field <code>uint32 reconnectCount = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setReconnectCount($var)
    {
        GPBUtil::checkUint32($var);
        $this->reconnectCount = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 lastErrorCode = 4;</code>
     * @return int
     */
    public function getLastErrorCode()
    {
        return $this->lastErrorCode;
    }

    /**
     * Generated from protobuf field <code>uint32 lastErrorCode = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setLastErrorCode($var)
    {
        GPBUtil::checkUint32($var);
        $this->lastErrorCode = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string expTag = 5;</code>
     * @return string
     */
    public function getExpTag()
    {
        return $this->expTag;
    }

    /**
     * Generated from protobuf field <code>string expTag = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setExpTag($var)
    {
        GPBUtil::checkString($var, True);
        $this->expTag = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string attach = 6;</code>
     * @return string
     */
    public function getAttach()
    {
        return $this->attach;
    }

    /**
     * Generated from protobuf field <code>string attach = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setAttach($var)
    {
        GPBUtil::checkString($var, True);
        $this->attach = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string pageId = 7;</code>
     * @return string
     */
    public function getPageId()
    {
        return $this->pageId;
    }

    /**
     * Generated from protobuf field <code>string pageId = 7;</code>
     * @param string $var
     * @return $this
     */
    public function setPageId($var)
    {
        GPBUtil::checkString($var, True);
        $this->pageId = $var;

        return $this;
    }

}

