<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: KS.proto

namespace KuaiShouLive;

if (false) {
    /**
     * This class is deprecated. Use KuaiShouLive\LiveAudienceState\AssistantType instead.
     * @deprecated
     */
    class LiveAudienceState_AssistantType {}
}
class_exists(LiveAudienceState\AssistantType::class);
@trigger_error('KuaiShouLive\LiveAudienceState_AssistantType is deprecated and will be removed in the next major release. Use KuaiShouLive\LiveAudienceState\AssistantType instead', E_USER_DEPRECATED);

