<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: KS.proto

namespace KuaiShouLive;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>KuaiShouLive.LiveAudienceState</code>
 */
class LiveAudienceState extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>bool isFromFansTop = 1;</code>
     */
    private $isFromFansTop = false;
    /**
     * Generated from protobuf field <code>bool isKoi = 2;</code>
     */
    private $isKoi = false;
    /**
     * Generated from protobuf field <code>.KuaiShouLive.LiveAudienceState.AssistantType assistantType = 3;</code>
     */
    private $assistantType = 0;
    /**
     * Generated from protobuf field <code>uint32 fansGroupIntimacyLevel = 4;</code>
     */
    private $fansGroupIntimacyLevel = 0;
    /**
     * Generated from protobuf field <code>.KuaiShouLive.GzoneNameplate nameplate = 5;</code>
     */
    private $nameplate = null;
    /**
     * Generated from protobuf field <code>.KuaiShouLive.LiveFansGroupState liveFansGroupState = 6;</code>
     */
    private $liveFansGroupState = null;
    /**
     * Generated from protobuf field <code>uint32 wealthGrade = 7;</code>
     */
    private $wealthGrade = 0;
    /**
     * Generated from protobuf field <code>string badgeKey = 8;</code>
     */
    private $badgeKey = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type bool $isFromFansTop
     *     @type bool $isKoi
     *     @type int $assistantType
     *     @type int $fansGroupIntimacyLevel
     *     @type \KuaiShouLive\GzoneNameplate $nameplate
     *     @type \KuaiShouLive\LiveFansGroupState $liveFansGroupState
     *     @type int $wealthGrade
     *     @type string $badgeKey
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\KS::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>bool isFromFansTop = 1;</code>
     * @return bool
     */
    public function getIsFromFansTop()
    {
        return $this->isFromFansTop;
    }

    /**
     * Generated from protobuf field <code>bool isFromFansTop = 1;</code>
     * @param bool $var
     * @return $this
     */
    public function setIsFromFansTop($var)
    {
        GPBUtil::checkBool($var);
        $this->isFromFansTop = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool isKoi = 2;</code>
     * @return bool
     */
    public function getIsKoi()
    {
        return $this->isKoi;
    }

    /**
     * Generated from protobuf field <code>bool isKoi = 2;</code>
     * @param bool $var
     * @return $this
     */
    public function setIsKoi($var)
    {
        GPBUtil::checkBool($var);
        $this->isKoi = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.KuaiShouLive.LiveAudienceState.AssistantType assistantType = 3;</code>
     * @return int
     */
    public function getAssistantType()
    {
        return $this->assistantType;
    }

    /**
     * Generated from protobuf field <code>.KuaiShouLive.LiveAudienceState.AssistantType assistantType = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setAssistantType($var)
    {
        GPBUtil::checkEnum($var, \KuaiShouLive\LiveAudienceState_AssistantType::class);
        $this->assistantType = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 fansGroupIntimacyLevel = 4;</code>
     * @return int
     */
    public function getFansGroupIntimacyLevel()
    {
        return $this->fansGroupIntimacyLevel;
    }

    /**
     * Generated from protobuf field <code>uint32 fansGroupIntimacyLevel = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setFansGroupIntimacyLevel($var)
    {
        GPBUtil::checkUint32($var);
        $this->fansGroupIntimacyLevel = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.KuaiShouLive.GzoneNameplate nameplate = 5;</code>
     * @return \KuaiShouLive\GzoneNameplate
     */
    public function getNameplate()
    {
        return $this->nameplate;
    }

    /**
     * Generated from protobuf field <code>.KuaiShouLive.GzoneNameplate nameplate = 5;</code>
     * @param \KuaiShouLive\GzoneNameplate $var
     * @return $this
     */
    public function setNameplate($var)
    {
        GPBUtil::checkMessage($var, \KuaiShouLive\GzoneNameplate::class);
        $this->nameplate = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.KuaiShouLive.LiveFansGroupState liveFansGroupState = 6;</code>
     * @return \KuaiShouLive\LiveFansGroupState
     */
    public function getLiveFansGroupState()
    {
        return $this->liveFansGroupState;
    }

    /**
     * Generated from protobuf field <code>.KuaiShouLive.LiveFansGroupState liveFansGroupState = 6;</code>
     * @param \KuaiShouLive\LiveFansGroupState $var
     * @return $this
     */
    public function setLiveFansGroupState($var)
    {
        GPBUtil::checkMessage($var, \KuaiShouLive\LiveFansGroupState::class);
        $this->liveFansGroupState = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 wealthGrade = 7;</code>
     * @return int
     */
    public function getWealthGrade()
    {
        return $this->wealthGrade;
    }

    /**
     * Generated from protobuf field <code>uint32 wealthGrade = 7;</code>
     * @param int $var
     * @return $this
     */
    public function setWealthGrade($var)
    {
        GPBUtil::checkUint32($var);
        $this->wealthGrade = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string badgeKey = 8;</code>
     * @return string
     */
    public function getBadgeKey()
    {
        return $this->badgeKey;
    }

    /**
     * Generated from protobuf field <code>string badgeKey = 8;</code>
     * @param string $var
     * @return $this
     */
    public function setBadgeKey($var)
    {
        GPBUtil::checkString($var, True);
        $this->badgeKey = $var;

        return $this;
    }

}

