<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: KS.proto

namespace KuaiShouLive;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>KuaiShouLive.PicUrl</code>
 */
class PicUrl extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string cdn = 1;</code>
     */
    private $cdn = '';
    /**
     * Generated from protobuf field <code>string url = 2;</code>
     */
    private $url = '';
    /**
     * Generated from protobuf field <code>string urlPattern = 3;</code>
     */
    private $urlPattern = '';
    /**
     * Generated from protobuf field <code>string ip = 4;</code>
     */
    private $ip = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $cdn
     *     @type string $url
     *     @type string $urlPattern
     *     @type string $ip
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\KS::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string cdn = 1;</code>
     * @return string
     */
    public function getCdn()
    {
        return $this->cdn;
    }

    /**
     * Generated from protobuf field <code>string cdn = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setCdn($var)
    {
        GPBUtil::checkString($var, True);
        $this->cdn = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string url = 2;</code>
     * @return string
     */
    public function getUrl()
    {
        return $this->url;
    }

    /**
     * Generated from protobuf field <code>string url = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setUrl($var)
    {
        GPBUtil::checkString($var, True);
        $this->url = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string urlPattern = 3;</code>
     * @return string
     */
    public function getUrlPattern()
    {
        return $this->urlPattern;
    }

    /**
     * Generated from protobuf field <code>string urlPattern = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setUrlPattern($var)
    {
        GPBUtil::checkString($var, True);
        $this->urlPattern = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string ip = 4;</code>
     * @return string
     */
    public function getIp()
    {
        return $this->ip;
    }

    /**
     * Generated from protobuf field <code>string ip = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setIp($var)
    {
        GPBUtil::checkString($var, True);
        $this->ip = $var;

        return $this;
    }

}

