<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: KuaiShouLive.proto

namespace KuaiShouLive;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>KuaiShouLive.SCPingAck</code>
 */
class SCPingAck extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string echoData = 1;</code>
     */
    private $echoData = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $echoData
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\KuaiShouLive::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string echoData = 1;</code>
     * @return string
     */
    public function getEchoData()
    {
        return $this->echoData;
    }

    /**
     * Generated from protobuf field <code>string echoData = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setEchoData($var)
    {
        GPBUtil::checkString($var, True);
        $this->echoData = $var;

        return $this;
    }

}

