<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: KS.proto

namespace KuaiShouLive;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>KuaiShouLive.SCWebFeedPush</code>
 */
class SCWebFeedPush extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string displayWatchingCount = 1;</code>
     */
    private $displayWatchingCount = '';
    /**
     * Generated from protobuf field <code>string displayLikeCount = 2;</code>
     */
    private $displayLikeCount = '';
    /**
     * Generated from protobuf field <code>uint64 pendingLikeCount = 3;</code>
     */
    private $pendingLikeCount = 0;
    /**
     * Generated from protobuf field <code>uint64 pushInterval = 4;</code>
     */
    private $pushInterval = 0;
    /**
     * Generated from protobuf field <code>.KuaiShouLive.WebCommentFeed commentFeeds = 5;</code>
     */
    private $commentFeeds = null;
    /**
     * Generated from protobuf field <code>string commentCursor = 6;</code>
     */
    private $commentCursor = '';
    /**
     * Generated from protobuf field <code>.KuaiShouLive.WebComboCommentFeed comboCommentFeed = 7;</code>
     */
    private $comboCommentFeed = null;
    /**
     * Generated from protobuf field <code>.KuaiShouLive.WebLikeFeed likeFeeds = 8;</code>
     */
    private $likeFeeds = null;
    /**
     * Generated from protobuf field <code>.KuaiShouLive.WebGiftFeed giftFeeds = 9;</code>
     */
    private $giftFeeds = null;
    /**
     * Generated from protobuf field <code>string giftCursor = 10;</code>
     */
    private $giftCursor = '';
    /**
     * Generated from protobuf field <code>.KuaiShouLive.WebSystemNoticeFeed systemNoticeFeeds = 11;</code>
     */
    private $systemNoticeFeeds = null;
    /**
     * Generated from protobuf field <code>.KuaiShouLive.WebShareFeed shareFeeds = 12;</code>
     */
    private $shareFeeds = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $displayWatchingCount
     *     @type string $displayLikeCount
     *     @type int|string $pendingLikeCount
     *     @type int|string $pushInterval
     *     @type \KuaiShouLive\WebCommentFeed $commentFeeds
     *     @type string $commentCursor
     *     @type \KuaiShouLive\WebComboCommentFeed $comboCommentFeed
     *     @type \KuaiShouLive\WebLikeFeed $likeFeeds
     *     @type \KuaiShouLive\WebGiftFeed $giftFeeds
     *     @type string $giftCursor
     *     @type \KuaiShouLive\WebSystemNoticeFeed $systemNoticeFeeds
     *     @type \KuaiShouLive\WebShareFeed $shareFeeds
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\KS::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string displayWatchingCount = 1;</code>
     * @return string
     */
    public function getDisplayWatchingCount()
    {
        return $this->displayWatchingCount;
    }

    /**
     * Generated from protobuf field <code>string displayWatchingCount = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setDisplayWatchingCount($var)
    {
        GPBUtil::checkString($var, True);
        $this->displayWatchingCount = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string displayLikeCount = 2;</code>
     * @return string
     */
    public function getDisplayLikeCount()
    {
        return $this->displayLikeCount;
    }

    /**
     * Generated from protobuf field <code>string displayLikeCount = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setDisplayLikeCount($var)
    {
        GPBUtil::checkString($var, True);
        $this->displayLikeCount = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 pendingLikeCount = 3;</code>
     * @return int|string
     */
    public function getPendingLikeCount()
    {
        return $this->pendingLikeCount;
    }

    /**
     * Generated from protobuf field <code>uint64 pendingLikeCount = 3;</code>
     * @param int|string $var
     * @return $this
     */
    public function setPendingLikeCount($var)
    {
        GPBUtil::checkUint64($var);
        $this->pendingLikeCount = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 pushInterval = 4;</code>
     * @return int|string
     */
    public function getPushInterval()
    {
        return $this->pushInterval;
    }

    /**
     * Generated from protobuf field <code>uint64 pushInterval = 4;</code>
     * @param int|string $var
     * @return $this
     */
    public function setPushInterval($var)
    {
        GPBUtil::checkUint64($var);
        $this->pushInterval = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.KuaiShouLive.WebCommentFeed commentFeeds = 5;</code>
     * @return \KuaiShouLive\WebCommentFeed
     */
    public function getCommentFeeds()
    {
        return $this->commentFeeds;
    }

    /**
     * Generated from protobuf field <code>.KuaiShouLive.WebCommentFeed commentFeeds = 5;</code>
     * @param \KuaiShouLive\WebCommentFeed $var
     * @return $this
     */
    public function setCommentFeeds($var)
    {
        GPBUtil::checkMessage($var, \KuaiShouLive\WebCommentFeed::class);
        $this->commentFeeds = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string commentCursor = 6;</code>
     * @return string
     */
    public function getCommentCursor()
    {
        return $this->commentCursor;
    }

    /**
     * Generated from protobuf field <code>string commentCursor = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setCommentCursor($var)
    {
        GPBUtil::checkString($var, True);
        $this->commentCursor = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.KuaiShouLive.WebComboCommentFeed comboCommentFeed = 7;</code>
     * @return \KuaiShouLive\WebComboCommentFeed
     */
    public function getComboCommentFeed()
    {
        return $this->comboCommentFeed;
    }

    /**
     * Generated from protobuf field <code>.KuaiShouLive.WebComboCommentFeed comboCommentFeed = 7;</code>
     * @param \KuaiShouLive\WebComboCommentFeed $var
     * @return $this
     */
    public function setComboCommentFeed($var)
    {
        GPBUtil::checkMessage($var, \KuaiShouLive\WebComboCommentFeed::class);
        $this->comboCommentFeed = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.KuaiShouLive.WebLikeFeed likeFeeds = 8;</code>
     * @return \KuaiShouLive\WebLikeFeed
     */
    public function getLikeFeeds()
    {
        return $this->likeFeeds;
    }

    /**
     * Generated from protobuf field <code>.KuaiShouLive.WebLikeFeed likeFeeds = 8;</code>
     * @param \KuaiShouLive\WebLikeFeed $var
     * @return $this
     */
    public function setLikeFeeds($var)
    {
        GPBUtil::checkMessage($var, \KuaiShouLive\WebLikeFeed::class);
        $this->likeFeeds = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.KuaiShouLive.WebGiftFeed giftFeeds = 9;</code>
     * @return \KuaiShouLive\WebGiftFeed
     */
    public function getGiftFeeds()
    {
        return $this->giftFeeds;
    }

    /**
     * Generated from protobuf field <code>.KuaiShouLive.WebGiftFeed giftFeeds = 9;</code>
     * @param \KuaiShouLive\WebGiftFeed $var
     * @return $this
     */
    public function setGiftFeeds($var)
    {
        GPBUtil::checkMessage($var, \KuaiShouLive\WebGiftFeed::class);
        $this->giftFeeds = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string giftCursor = 10;</code>
     * @return string
     */
    public function getGiftCursor()
    {
        return $this->giftCursor;
    }

    /**
     * Generated from protobuf field <code>string giftCursor = 10;</code>
     * @param string $var
     * @return $this
     */
    public function setGiftCursor($var)
    {
        GPBUtil::checkString($var, True);
        $this->giftCursor = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.KuaiShouLive.WebSystemNoticeFeed systemNoticeFeeds = 11;</code>
     * @return \KuaiShouLive\WebSystemNoticeFeed
     */
    public function getSystemNoticeFeeds()
    {
        return $this->systemNoticeFeeds;
    }

    /**
     * Generated from protobuf field <code>.KuaiShouLive.WebSystemNoticeFeed systemNoticeFeeds = 11;</code>
     * @param \KuaiShouLive\WebSystemNoticeFeed $var
     * @return $this
     */
    public function setSystemNoticeFeeds($var)
    {
        GPBUtil::checkMessage($var, \KuaiShouLive\WebSystemNoticeFeed::class);
        $this->systemNoticeFeeds = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.KuaiShouLive.WebShareFeed shareFeeds = 12;</code>
     * @return \KuaiShouLive\WebShareFeed
     */
    public function getShareFeeds()
    {
        return $this->shareFeeds;
    }

    /**
     * Generated from protobuf field <code>.KuaiShouLive.WebShareFeed shareFeeds = 12;</code>
     * @param \KuaiShouLive\WebShareFeed $var
     * @return $this
     */
    public function setShareFeeds($var)
    {
        GPBUtil::checkMessage($var, \KuaiShouLive\WebShareFeed::class);
        $this->shareFeeds = $var;

        return $this;
    }

}

