<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: KuaiShouLive.proto

namespace KuaiShouLive;

if (false) {
    /**
     * This class is deprecated. Use KuaiShouLive\SocketMessage\CompressionType instead.
     * @deprecated
     */
    class SocketMessage_CompressionType {}
}
class_exists(SocketMessage\CompressionType::class);
@trigger_error('KuaiShouLive\SocketMessage_CompressionType is deprecated and will be removed in the next major release. Use KuaiShouLive\SocketMessage\CompressionType instead', E_USER_DEPRECATED);

