<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: KuaiShouLive.proto

namespace KuaiShouLive;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>KuaiShouLive.SocketMessage</code>
 */
class SocketMessage extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.KuaiShouLive.PayloadType payloadType = 1;</code>
     */
    private $payloadType = 0;
    /**
     * Generated from protobuf field <code>.KuaiShouLive.SocketMessage.CompressionType compressionType = 2;</code>
     */
    private $compressionType = 0;
    /**
     * Generated from protobuf field <code>bytes payload = 3;</code>
     */
    private $payload = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $payloadType
     *     @type int $compressionType
     *     @type string $payload
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\KuaiShouLive::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.KuaiShouLive.PayloadType payloadType = 1;</code>
     * @return int
     */
    public function getPayloadType()
    {
        return $this->payloadType;
    }

    /**
     * Generated from protobuf field <code>.KuaiShouLive.PayloadType payloadType = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setPayloadType($var)
    {
        GPBUtil::checkEnum($var, \KuaiShouLive\PayloadType::class);
        $this->payloadType = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.KuaiShouLive.SocketMessage.CompressionType compressionType = 2;</code>
     * @return int
     */
    public function getCompressionType()
    {
        return $this->compressionType;
    }

    /**
     * Generated from protobuf field <code>.KuaiShouLive.SocketMessage.CompressionType compressionType = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setCompressionType($var)
    {
        GPBUtil::checkEnum($var, \KuaiShouLive\SocketMessage_CompressionType::class);
        $this->compressionType = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes payload = 3;</code>
     * @return string
     */
    public function getPayload()
    {
        return $this->payload;
    }

    /**
     * Generated from protobuf field <code>bytes payload = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setPayload($var)
    {
        GPBUtil::checkString($var, False);
        $this->payload = $var;

        return $this;
    }

}

