<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: KuaiShouLive.proto

namespace KuaiShouLive;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>KuaiShouLive.UserInfo</code>
 */
class UserInfo extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>uint64 userId = 1;</code>
     */
    private $userId = 0;
    /**
     * Generated from protobuf field <code>string userName = 2;</code>
     */
    private $userName = '';
    /**
     * Generated from protobuf field <code>string userGender = 3;</code>
     */
    private $userGender = '';
    /**
     * Generated from protobuf field <code>string userText = 4;</code>
     */
    private $userText = '';
    /**
     * Generated from protobuf field <code>repeated .KuaiShouLive.PicUrl headUrls = 5;</code>
     */
    private $headUrls;
    /**
     * Generated from protobuf field <code>bool verified = 6;</code>
     */
    private $verified = false;
    /**
     * Generated from protobuf field <code>string sUserId = 7;</code>
     */
    private $sUserId = '';
    /**
     * Generated from protobuf field <code>repeated .KuaiShouLive.PicUrl httpsHeadUrls = 8;</code>
     */
    private $httpsHeadUrls;
    /**
     * Generated from protobuf field <code>string kwaiId = 9;</code>
     */
    private $kwaiId = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $userId
     *     @type string $userName
     *     @type string $userGender
     *     @type string $userText
     *     @type \KuaiShouLive\PicUrl[]|\Google\Protobuf\Internal\RepeatedField $headUrls
     *     @type bool $verified
     *     @type string $sUserId
     *     @type \KuaiShouLive\PicUrl[]|\Google\Protobuf\Internal\RepeatedField $httpsHeadUrls
     *     @type string $kwaiId
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\KuaiShouLive::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>uint64 userId = 1;</code>
     * @return int|string
     */
    public function getUserId()
    {
        return $this->userId;
    }

    /**
     * Generated from protobuf field <code>uint64 userId = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setUserId($var)
    {
        GPBUtil::checkUint64($var);
        $this->userId = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string userName = 2;</code>
     * @return string
     */
    public function getUserName()
    {
        return $this->userName;
    }

    /**
     * Generated from protobuf field <code>string userName = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setUserName($var)
    {
        GPBUtil::checkString($var, True);
        $this->userName = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string userGender = 3;</code>
     * @return string
     */
    public function getUserGender()
    {
        return $this->userGender;
    }

    /**
     * Generated from protobuf field <code>string userGender = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setUserGender($var)
    {
        GPBUtil::checkString($var, True);
        $this->userGender = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string userText = 4;</code>
     * @return string
     */
    public function getUserText()
    {
        return $this->userText;
    }

    /**
     * Generated from protobuf field <code>string userText = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setUserText($var)
    {
        GPBUtil::checkString($var, True);
        $this->userText = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .KuaiShouLive.PicUrl headUrls = 5;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getHeadUrls()
    {
        return $this->headUrls;
    }

    /**
     * Generated from protobuf field <code>repeated .KuaiShouLive.PicUrl headUrls = 5;</code>
     * @param \KuaiShouLive\PicUrl[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setHeadUrls($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \KuaiShouLive\PicUrl::class);
        $this->headUrls = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool verified = 6;</code>
     * @return bool
     */
    public function getVerified()
    {
        return $this->verified;
    }

    /**
     * Generated from protobuf field <code>bool verified = 6;</code>
     * @param bool $var
     * @return $this
     */
    public function setVerified($var)
    {
        GPBUtil::checkBool($var);
        $this->verified = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string sUserId = 7;</code>
     * @return string
     */
    public function getSUserId()
    {
        return $this->sUserId;
    }

    /**
     * Generated from protobuf field <code>string sUserId = 7;</code>
     * @param string $var
     * @return $this
     */
    public function setSUserId($var)
    {
        GPBUtil::checkString($var, True);
        $this->sUserId = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .KuaiShouLive.PicUrl httpsHeadUrls = 8;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getHttpsHeadUrls()
    {
        return $this->httpsHeadUrls;
    }

    /**
     * Generated from protobuf field <code>repeated .KuaiShouLive.PicUrl httpsHeadUrls = 8;</code>
     * @param \KuaiShouLive\PicUrl[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setHttpsHeadUrls($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \KuaiShouLive\PicUrl::class);
        $this->httpsHeadUrls = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string kwaiId = 9;</code>
     * @return string
     */
    public function getKwaiId()
    {
        return $this->kwaiId;
    }

    /**
     * Generated from protobuf field <code>string kwaiId = 9;</code>
     * @param string $var
     * @return $this
     */
    public function setKwaiId($var)
    {
        GPBUtil::checkString($var, True);
        $this->kwaiId = $var;

        return $this;
    }

}

