<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: KS.proto

namespace KuaiShouLive;

/**
 * Protobuf type <code>KuaiShouLive.WebCommentFeedShowType</code>
 */
class WebCommentFeedShowType
{
    /**
     * Generated from protobuf enum <code>FEED_SHOW_UNKNOWN = 0;</code>
     */
    const FEED_SHOW_UNKNOWN = 0;
    /**
     * Generated from protobuf enum <code>FEED_SHOW_NORMAL = 1;</code>
     */
    const FEED_SHOW_NORMAL = 1;
    /**
     * Generated from protobuf enum <code>FEED_HIDDEN = 2;</code>
     */
    const FEED_HIDDEN = 2;
}

