<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: KuaiShouLive.proto

namespace KuaiShouLive;

if (false) {
    /**
     * This class is deprecated. Use KuaiShouLive\WebGiftFeed\StyleType instead.
     * @deprecated
     */
    class WebGiftFeed_StyleType {}
}
class_exists(WebGiftFeed\StyleType::class);
@trigger_error('KuaiShouLive\WebGiftFeed_StyleType is deprecated and will be removed in the next major release. Use KuaiShouLive\WebGiftFeed\StyleType instead', E_USER_DEPRECATED);

