<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: KuaiShouLive.proto

namespace KuaiShouLive;

/**
 * Protobuf type <code>KuaiShouLive.WebLiveAssistantType</code>
 */
class WebLiveAssistantType
{
    /**
     * Generated from protobuf enum <code>UNKNOWN_ASSISTANT_TYPE = 0;</code>
     */
    const UNKNOWN_ASSISTANT_TYPE = 0;
    /**
     * Generated from protobuf enum <code>SUPER = 1;</code>
     */
    const SUPER = 1;
    /**
     * Generated from protobuf enum <code>JUNIOR = 2;</code>
     */
    const JUNIOR = 2;
}

