<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: KuaiShouLive.proto

namespace KuaiShouLive;

/**
 * Protobuf type <code>KuaiShouLive.WebPauseType</code>
 */
class WebPauseType
{
    /**
     * Generated from protobuf enum <code>UNKNOWN_PAUSE_TYPE = 0;</code>
     */
    const UNKNOWN_PAUSE_TYPE = 0;
    /**
     * Generated from protobuf enum <code>TELEPHONE = 1;</code>
     */
    const TELEPHONE = 1;
    /**
     * Generated from protobuf enum <code>SHARE = 2;</code>
     */
    const SHARE = 2;
}

