<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: KuaiShouLive.proto

namespace KuaiShouLive;

/**
 * Protobuf type <code>KuaiShouLive.WebUserPauseType</code>
 */
class WebUserPauseType
{
    /**
     * Generated from protobuf enum <code>UNKNOWN_USER_PAUSE_TYPE = 0;</code>
     */
    const UNKNOWN_USER_PAUSE_TYPE = 0;
    /**
     * Generated from protobuf enum <code>BACKGROUND = 1;</code>
     */
    const BACKGROUND = 1;
}

