<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: KuaiShouLive.proto

namespace KuaiShouLive;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>KuaiShouLive.WebWatchingUserInfo</code>
 */
class WebWatchingUserInfo extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.KuaiShouLive.SimpleUserInfo user = 1;</code>
     */
    private $user = null;
    /**
     * Generated from protobuf field <code>bool offline = 2;</code>
     */
    private $offline = false;
    /**
     * Generated from protobuf field <code>bool tuhao = 3;</code>
     */
    private $tuhao = false;
    /**
     * Generated from protobuf field <code>.KuaiShouLive.WebLiveAssistantType liveAssistantType = 4;</code>
     */
    private $liveAssistantType = 0;
    /**
     * Generated from protobuf field <code>string displayKsCoin = 5;</code>
     */
    private $displayKsCoin = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \KuaiShouLive\SimpleUserInfo $user
     *     @type bool $offline
     *     @type bool $tuhao
     *     @type int $liveAssistantType
     *     @type string $displayKsCoin
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\KuaiShouLive::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.KuaiShouLive.SimpleUserInfo user = 1;</code>
     * @return \KuaiShouLive\SimpleUserInfo
     */
    public function getUser()
    {
        return $this->user;
    }

    /**
     * Generated from protobuf field <code>.KuaiShouLive.SimpleUserInfo user = 1;</code>
     * @param \KuaiShouLive\SimpleUserInfo $var
     * @return $this
     */
    public function setUser($var)
    {
        GPBUtil::checkMessage($var, \KuaiShouLive\SimpleUserInfo::class);
        $this->user = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool offline = 2;</code>
     * @return bool
     */
    public function getOffline()
    {
        return $this->offline;
    }

    /**
     * Generated from protobuf field <code>bool offline = 2;</code>
     * @param bool $var
     * @return $this
     */
    public function setOffline($var)
    {
        GPBUtil::checkBool($var);
        $this->offline = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool tuhao = 3;</code>
     * @return bool
     */
    public function getTuhao()
    {
        return $this->tuhao;
    }

    /**
     * Generated from protobuf field <code>bool tuhao = 3;</code>
     * @param bool $var
     * @return $this
     */
    public function setTuhao($var)
    {
        GPBUtil::checkBool($var);
        $this->tuhao = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.KuaiShouLive.WebLiveAssistantType liveAssistantType = 4;</code>
     * @return int
     */
    public function getLiveAssistantType()
    {
        return $this->liveAssistantType;
    }

    /**
     * Generated from protobuf field <code>.KuaiShouLive.WebLiveAssistantType liveAssistantType = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setLiveAssistantType($var)
    {
        GPBUtil::checkEnum($var, \KuaiShouLive\WebLiveAssistantType::class);
        $this->liveAssistantType = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string displayKsCoin = 5;</code>
     * @return string
     */
    public function getDisplayKsCoin()
    {
        return $this->displayKsCoin;
    }

    /**
     * Generated from protobuf field <code>string displayKsCoin = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setDisplayKsCoin($var)
    {
        GPBUtil::checkString($var, True);
        $this->displayKsCoin = $var;

        return $this;
    }

}

