<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: KS.proto

namespace KuaiShouPack\SocketMessage;

/**
 * Protobuf type <code>KuaiShouPack.SocketMessage.CompressionType</code>
 */
class CompressionType
{
    /**
     * Generated from protobuf enum <code>UNKNOWN = 0;</code>
     */
    const UNKNOWN = 0;
    /**
     * Generated from protobuf enum <code>NONE = 1;</code>
     */
    const NONE = 1;
    /**
     * Generated from protobuf enum <code>GZIP = 2;</code>
     */
    const GZIP = 2;
    /**
     * Generated from protobuf enum <code>AES = 3;</code>
     */
    const AES = 3;
}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(CompressionType::class, \KuaiShouPack\SocketMessage_CompressionType::class);

