<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: KS.proto

namespace KuaiShouLive\LiveAudienceState;

/**
 * Protobuf type <code>KuaiShouLive.LiveAudienceState.AssistantType</code>
 */
class AssistantType
{
    /**
     * Generated from protobuf enum <code>UNKNOWN_ASSISTANT_TYPE = 0;</code>
     */
    const UNKNOWN_ASSISTANT_TYPE = 0;
    /**
     * Generated from protobuf enum <code>SUPER = 1;</code>
     */
    const SUPER = 1;
    /**
     * Generated from protobuf enum <code>JUNIOR = 2;</code>
     */
    const JUNIOR = 2;
}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(AssistantType::class, \KuaiShouLive\LiveAudienceState_AssistantType::class);

